CREATE TABLE messages_homepage (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  message VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE link_shortened (
  id SERIAL PRIMARY KEY,
  original_link VARCHAR(2048) NOT NULL,
  shorted_link VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)